name: Build Knio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Options: 'zulu', 'adopt', 'temurin'
          java-version: '21'  # Specify the Java version

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build
